name: Banking CI Pipeline

on:
  - push
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake lcov

      - name: Configure and compile project
        run: |
          cd banking
          mkdir -p build
          cd build
          cmake .. -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON
          make

      - name: Execute unit tests
        run: |
          cd banking/build
          ctest --output-on-failure

      - name: Generate coverage data
        run: |
          cd banking/build
          lcov --ignore-errors mismatch --ignore-errors gcov --capture --directory . -o coverage.info || lcov --ignore-errors gcov --capture --directory . -o coverage.info
          lcov --extract coverage.info \
            "*/banking/Account.cpp" \
            "*/banking/Account.h" \
            "*/banking/Transaction.cpp" \
            "*/banking/Transaction.h" \
            -o filtered_coverage.info

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: banking/build/filtered_coverage.info
